name: Gerar APK Rodrigues
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Instalar Dependencias
        run: npm install

      - name: Gerar Pasta Dist (Build React)
        run: npm run build

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Inicializar e Compilar Android
        run: |
          # Se a pasta android não existir, ele cria agora
          npx cap add android || true
          npx cap sync android
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Baixar o APK Pronto
        uses: actions/upload-artifact@v4
        with:
          name: app-entregador-rodrigues
          path: android/app/build/outputs/apk/debug/app-debug.apk