name: Gerar APK Rodrigues

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Codigo
        uses: actions/checkout@v4
      
      - name: Configurar Node.js (Versao Requerida pelo Capacitor)
        uses: actions/setup-node@v4
        with:
          node-version: 22  # Atualizado para v22 para evitar o erro de compatibilidade do Capacitor CLI
          
      - name: Instalar Ferramentas e Dependencias
        run: |
          npm install
          # Instalando o motor do Capacitor e plugins nativos explicitamente
          npm install @capacitor/cli @capacitor/core @capacitor/android @capacitor/geolocation @capacitor/camera @capacitor/haptics @capacitor/network @capacitor/device

      - name: Gerar Pasta Dist (Build React)
        run: npm run build

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21' # 

      - name: Sincronizar Projeto Android NATIVO
        run: |
          # Garante que a pasta android existe e injeta o codigo do site dentro dela
          npx cap add android || true
          npx cap sync android

      - name: Compilar APK Final (Gradle)
        run: |
          cd android
          # Dá permissão de execução ao motor de build do Android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: app-entregador-rodrigues
          path: android/app/build/outputs/apk/debug/app-debug.apk